import { jsPDF } from "jspdf";
import QRCode from "qrcode";

export type DiagnosisRow = {
  id: string;
  created_at: string;
  component_name: string | null;
  package_type: string | null;
  manufacturer: string | null;
  visible_damage: string[] | null;
  severity: string | null;
  possible_cause: string | null;
  summary: string | null;
  recommended_action: string | null;
  repairability: string | null;
  recommendations: string[] | null;
  confidence: number | null;
  status: string;
  image_path: string;
  source: string;
  user_id: string;
};

export async function buildReportPdf(
  d: DiagnosisRow,
  imageDataUrl: string | null,
  technician: string,
): Promise<Blob> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 0;

  doc.setFillColor(24, 38, 62);
  doc.rect(0, 0, W, 78, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("SMART MULTI-TESTER", 40, 34);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("AI Diagnostic Report — Electronic Component / IC Analysis", 40, 54);
  y = 106;

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.text(`Report ID: ${d.id}`, 40, y);
  doc.text(`Date: ${new Date(d.created_at).toLocaleString()}`, 40, y + 16);
  doc.text(`Technician: ${technician}`, 40, y + 32);
  doc.text(`AI Confidence: ${d.confidence ?? 0}%`, 40, y + 48);

  try {
    const qr = await QRCode.toDataURL(`smt-report:${d.id}`, { margin: 0, width: 220 });
    doc.addImage(qr, "PNG", W - 130, y - 10, 90, 90);
  } catch {
    /* QR is decorative */
  }
  y += 76;

  if (imageDataUrl) {
    try {
      doc.addImage(imageDataUrl, "JPEG", 40, y, 200, 150);
    } catch {
      /* unsupported image */
    }
  }

  const infoX = imageDataUrl ? 260 : 40;
  let iy = y + 12;
  const info: [string, string][] = [
    ["Component", d.component_name ?? "—"],
    ["Package", d.package_type ?? "—"],
    ["Manufacturer", d.manufacturer ?? "—"],
    ["Status", d.status.replace(/_/g, " ")],
    ["Severity", d.severity ?? "—"],
    ["Repairability", d.repairability ?? "—"],
  ];
  doc.setFontSize(10);
  for (const [k, v] of info) {
    doc.setFont("helvetica", "bold");
    doc.text(`${k}:`, infoX, iy);
    doc.setFont("helvetica", "normal");
    doc.text(String(v), infoX + 84, iy);
    iy += 16;
  }
  y = Math.max(y + 170, iy + 10);

  const section = (title: string, body: string[]) => {
    if (y > 720) {
      doc.addPage();
      y = 60;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(title, 40, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    for (const line of body) {
      const wrapped = doc.splitTextToSize(line, W - 90) as string[];
      for (const w of wrapped) {
        if (y > 780) {
          doc.addPage();
          y = 60;
        }
        doc.text(w, 46, y);
        y += 14;
      }
    }
    y += 10;
  };

  section("Diagnosis Summary", [d.summary ?? "—"]);
  section(
    "Visible Damage",
    d.visible_damage?.length ? d.visible_damage.map((x) => `• ${x}`) : ["• None detected"],
  );
  section("Possible Cause", [d.possible_cause ?? "—"]);
  section("Recommended Action", [d.recommended_action ?? "—"]);
  section(
    "Recommendations",
    d.recommendations?.length ? d.recommendations.map((x) => `• ${x}`) : ["• —"],
  );
  if ((d.confidence ?? 0) < 70) {
    section("Warning", ["Confidence below 70% — manual inspection recommended."]);
  }

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Generated by Smart Multi-Tester AI. Visual inspection only — verify electrically before final judgement.",
    40,
    820,
  );

  return doc.output("blob");
}
